name: azzoa_grocery
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  http: ^0.12.0+4
  fluttertoast: ^3.1.3
  intl: ^0.15.3
  shared_preferences: ^0.5.8
  webview_flutter: ^0.3.21
  google_sign_in: ^4.5.4
  flutter_facebook_login: ^3.0.0
  flutter_local_notifications: ^1.4.3
  url_launcher: ^5.4.7
  firebase_core: ^0.5.2
  firebase_messaging: ^7.0.3
  firebase_crashlytics: ^0.2.3
  pinput: ^0.2.4
  provider:
  flutter_rating_bar: ^3.0.1+1
  json_annotation: ^3.0.0
  google_maps_flutter: ^1.0.2
  image_picker: ^0.6.7+4
#  google_map_location_picker: ^4.1.3
  carousel_slider: ^2.3.1
  geolocator: ^6.0.0+4
  firebase_database: ^4.1.1
  sms_autofill: 2.2.0
  flutter_spinkit: ^4.1.2+1
  sqflite: ^1.3.2+1
  path: ^1.7.0
  country_list_pick: ^1.0.1+2

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^3.2.0
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - images/
    - i18n/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/roboto_regular.ttf
          weight: 400
        - asset: fonts/roboto_medium.ttf
          weight: 600
        - asset: fonts/roboto_bold.ttf
          weight: 700
